os: linux
language: minimal
compiler: gcc

before_install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
  - tar -zxvf cmake-3.15.2.tar.gz
  - cd cmake-3.15.2
  - ./bootstrap
  - make
  - sudo make install
  - sudo apt install cmake
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libgtest-dev

addons:
  apt:
    packages:
      - g++
      - cmake

jobs:
  include:
    - name: "checks"
      script:
        - mkdir _build
        - cd _build
        - cmake .. && make && ./client test

notifications:
  email: false