os: linux
language: minimal
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - cmake

jobs:
  include:
    - name: "checks"
      script:
        - cmake . && make && ./client test

notifications:
  email: false